-- Consolidates the historical root-level SQL scripts.
-- This migration adopts databases previously managed with Hibernate ddl-auto.

ALTER TABLE IF EXISTS public.users
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS profile_image_url TEXT,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL,
    ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL;

UPDATE public.users
SET created_at = NOW()
WHERE created_at IS NULL;

ALTER TABLE IF EXISTS public.users
    ALTER COLUMN created_at SET DEFAULT NOW(),
    ALTER COLUMN created_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_users_created_at
    ON public.users (created_at);
CREATE INDEX IF NOT EXISTS idx_users_deleted_at
    ON public.users (deleted_at);

ALTER TABLE IF EXISTS public.tournaments
    ADD COLUMN IF NOT EXISTS detalles TEXT,
    ADD COLUMN IF NOT EXISTS image_url TEXT,
    ADD COLUMN IF NOT EXISTS moderation_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS moderated_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS moderated_by_admin_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS moderation_reason TEXT NULL;

UPDATE public.tournaments
SET moderation_status = 'ACTIVE'
WHERE moderation_status IS NULL;

CREATE INDEX IF NOT EXISTS idx_tournaments_moderation_status
    ON public.tournaments (moderation_status);

CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT,
    related_entity_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id
    ON public.notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read
    ON public.notifications (is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at
    ON public.notifications (created_at);

ALTER TABLE public.notifications
    DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE public.notifications
    ADD CONSTRAINT notifications_type_check CHECK (type IN (
        'WELCOME',
        'TOURNAMENT_CANCELED',
        'TOURNAMENT_UPDATED',
        'TEAM_REMOVED',
        'TOURNAMENT_STARTED',
        'TOURNAMENT_FINALIZED',
        'MATCH_SCHEDULED',
        'MATCH_RESULT',
        'REGISTRATION_CONFIRMED',
        'TOURNAMENT_FULL',
        'TOURNAMENT_REMINDER',
        'TOURNAMENT_DEACTIVATED_BY_ADMIN',
        'TOURNAMENT_REACTIVATED_BY_ADMIN',
        'TOURNAMENT_LEFT',
        'TEAM_WITHDRAWN',
        'GENERAL',
        'NUEVO_COMENTARIO_POST',
        'RESPUESTA_COMENTARIO',
        'CONTACTO_AVISO'
    ));

CREATE TABLE IF NOT EXISTS public.organizer_role_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id),
    status VARCHAR(20) NOT NULL,
    message VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT,
    review_note VARCHAR(500),
    reject_reason VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_organizer_role_requests_user_id
    ON public.organizer_role_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_organizer_role_requests_status
    ON public.organizer_role_requests (status);
CREATE INDEX IF NOT EXISTS idx_organizer_role_requests_created_at
    ON public.organizer_role_requests (created_at);

COMMENT ON COLUMN public.users.profile_image_url IS
    'URL de la imagen de perfil del usuario almacenada en Supabase Storage';
COMMENT ON COLUMN public.tournaments.image_url IS
    'URL de la imagen del torneo almacenada en Supabase Storage';
